AWSTemplateFormatVersion: "2010-09-09"
Description: Amazon SES
Parameters:
  DomainName:
    Type: String
    Description: Domain name
  ZoneId:
    Type: AWS::Route53::HostedZone::Id
    Description: Route 53 zone ID
  EnableDmarcRecord:
    Type: String
    Description: Whether to enable DMARC record or not
    AllowedValues:
      - "true"
      - "false"
    Default: "true"
  DmarcPolicy:
    Type: String
    Description: DMARC policy
    AllowedValues:
      - "none"
      - "quarantine"
      - "reject"
    Default: quarantine
  DmarcReportAddr:
    Type: String
    Description: DMARC report receiver email address
    Default: ''
  ApplicationTag:
    Type: String
    Description: Application tag
  ApplicationId:
    Type: String
    Description: Application ARN
Conditions:
  IsDmarcEnabled:
    Fn::Equals:
      - !Ref EnableDmarcRecord
      - "true"
  HasDmarcReportDest:
    Fn::Not:
      - !Equals
        - !Ref DmarcReportAddr
        - ''
Resources:
  AppAssoc:
    Type: AWS::ServiceCatalogAppRegistry::ResourceAssociation
    Properties:
      Application: !Ref ApplicationId
      Resource: !Ref AWS::StackId
      ResourceType: CFN_STACK
  Topic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: !Sub "${AWS::StackName}-Topic"
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-Topic"
        - Key: CostTag
          Value: !Ref AWS::StackName
        - Key: AppManagerCFNStackKey
          Value: !Ref AWS::StackName
        - Key: awsApplication
          Value: !Ref ApplicationTag
  DefaultConfigSet:
    Type: AWS::SES::ConfigurationSet
    Properties:
      ReputationOptions:
        ReputationMetricsEnabled: true
      SendingOptions:
        SendingEnabled: true
  DefaultConfigSetEventDest:
    Type: AWS::SES::ConfigurationSetEventDestination
    Properties:
      ConfigurationSetName: !Ref DefaultConfigSet
      EventDestination:
        Enabled: true
        MatchingEventTypes:
          - reject
          - bounce
          - complaint
        SnsDestination:
          TopicARN: !Ref Topic
  Identity:
    Type: AWS::SES::EmailIdentity
    Properties:
      EmailIdentity: !Ref DomainName
      DkimAttributes:
        SigningEnabled: true
      DkimSigningAttributes:
        NextSigningKeyLength: RSA_2048_BIT
      ConfigurationSetAttributes:
        ConfigurationSetName: !Ref DefaultConfigSet
      MailFromAttributes:
        BehaviorOnMxFailure: USE_DEFAULT_VALUE
        MailFromDomain: !Sub "ses-${AWS::Region}.${DomainName}"
  DkimRecords:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      Comment: !Sub "${AWS::StackName} DKIM records"
      HostedZoneId: !Ref ZoneId
      RecordSets:
        - Name: !GetAtt Identity.DkimDNSTokenName1
          Type: CNAME
          TTL: "900"
          ResourceRecords:
            - !GetAtt Identity.DkimDNSTokenValue1
        - Name: !GetAtt Identity.DkimDNSTokenName2
          Type: CNAME
          TTL: "900"
          ResourceRecords:
            - !GetAtt Identity.DkimDNSTokenValue2
        - Name: !GetAtt Identity.DkimDNSTokenName3
          Type: CNAME
          TTL: "900"
          ResourceRecords:
            - !GetAtt Identity.DkimDNSTokenValue3
  SpfRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      Comment: SPF record
      HostedZoneId: !Ref ZoneId
      Name: !Sub "ses-${AWS::Region}.${DomainName}"
      Type: TXT
      TTL: "900"
      ResourceRecords:
        - '"v=spf1 include:amazonses.com ~all"'
  MxRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      Comment: MX record
      HostedZoneId: !Ref ZoneId
      Name: !Sub "ses-${AWS::Region}.${DomainName}"
      Type: MX
      TTL: "900"
      ResourceRecords:
        - !Sub "10 feedback-smtp.${AWS::Region}.amazonses.com"
  DmarcRecord:
    Type: AWS::Route53::RecordSet
    Condition: IsDmarcEnabled
    Properties:
      Comment: DMARC record
      HostedZoneId: !Ref ZoneId
      Name: !Sub "_dmarc.${DomainName}"
      Type: TXT
      TTL: "900"
      ResourceRecords:
        - !Join
          - ''
          - - '"v=DMARC1'
            - !Sub ';p=${DmarcPolicy}'
            - !If
              - HasDmarcReportDest
              - !Sub ';rua=mailto:${DmarcReportAddr}'
              - !Ref AWS::NoValue
            - ';adkim=r;aspf=r;pct=100'
            - '"'
