AWSTemplateFormatVersion: "2010-09-09"
Description: EC2 AWS role
Parameters:
  ApplicationTag:
    Type: String
    Description: Application tag
  ApplicationId:
    Type: String
    Description: Application ARN
Resources:
  AppAssoc:
    Type: AWS::ServiceCatalogAppRegistry::ResourceAssociation
    Properties:
      Application: !Ref ApplicationId
      Resource: !Ref AWS::StackId
      ResourceType: CFN_STACK
  Role:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action: sts:AssumeRole
            Principal:
              Service: ec2.amazonaws.com
      Path: !Sub "/${AWS::StackName}/"
      Description: EC2 SSM and CloudWatch role
      ManagedPolicyArns:
        - !Sub "arn:${AWS::Partition}:iam::aws:policy/AmazonSSMManagedInstanceCore"
        - !Sub "arn:${AWS::Partition}:iam::aws:policy/CloudWatchAgentServerPolicy"
      Policies:
        - PolicyName: AccessSSMParameters
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - ssm:GetParameter
                  - ssm:GetParameters
                  - ssm:PutParameter
                Resource: !Sub "arn:${AWS::Partition}:ssm:${AWS::Region}:${AWS::AccountId}:parameter/*"
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-Role"
        - Key: CostTag
          Value: !Ref AWS::StackName
        - Key: AppManagerCFNStackKey
          Value: !Ref AWS::StackName
        - Key: awsApplication
          Value: !Ref ApplicationTag
  InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref Role
      Path: !Sub "/${AWS::StackName}/"
