AWSTemplateFormatVersion: "2010-09-09"
Description: ECR
Parameters:
  ApplicationTag:
    Type: String
    Description: Application tag
  ApplicationId:
    Type: String
    Description: Application ARN
Resources:
  AppAssoc:
    Type: AWS::ServiceCatalogAppRegistry::ResourceAssociation
    Properties:
      Application: !Ref ApplicationId
      Resource: !Ref AWS::StackId
      ResourceType: CFN_STACK
  Repository:
    Type: AWS::ECR::Repository
    Properties:
      EmptyOnDelete: true
      LifecyclePolicy:
        LifecyclePolicyText: |
          {
            "rules": [
              {
                "rulePriority": 1,
                "description": "Delete untagged images",
                "selection": {
                  "tagStatus": "untagged",
                  "countType": "imageCountMoreThan",
                  "countNumber": 1
                },
                "action": {
                  "type": "expire"
                }
              }
            ]
          }
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-Repository"
        - Key: CostTag
          Value: !Ref AWS::StackName
        - Key: AppManagerCFNStackKey
          Value: !Ref AWS::StackName
        - Key: awsApplication
          Value: !Ref ApplicationTag
