AWSTemplateFormatVersion: "2010-09-09"
Description: Budget settings
Parameters:
  BudgetAmount:
    Type: Number
    Description: Budget amount in dollar
    Default: "100"
  AlarmTargetEmail:
    Type: String
    Description: Budget alarm target Email
Resources:
  Budget:
    Type: AWS::Budgets::Budget
    Properties:
      Budget:
        BudgetType: COST
        TimeUnit: MONTHLY
        BudgetLimit:
          Amount: !Ref BudgetAmount
          Unit: USD
      NotificationsWithSubscribers:
        - Notification:
            NotificationType: ACTUAL
            ComparisonOperator: GREATER_THAN
            Threshold: 80
          Subscribers:
            - SubscriptionType: EMAIL
              Address: !Ref AlarmTargetEmail
        - Notification:
            NotificationType: ACTUAL
            ComparisonOperator: GREATER_THAN
            Threshold: 100
          Subscribers:
            - SubscriptionType: EMAIL
              Address: !Ref AlarmTargetEmail
