AWSTemplateFormatVersion: "2010-09-09"
Description: Misskey RDS params and options
Parameters:
  Timezone:
    Type: String
    Description: Timezone
    Default: UTC
Resources:
  ParameterGroup:
    Type: AWS::RDS::DBParameterGroup
    Properties:
      Description: !Sub "${AWS::StackName} parameter group"
      Family: postgres15
      Parameters:
        timezone: !Ref Timezone
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-Topic"
        - Key: CostTag
          Value: !Ref AWS::StackName
        - Key: AppManagerCFNStackKey
          Value: !Ref AWS::StackName
  OptionsGroup:
    Type: AWS::RDS::OptionGroup
    Properties:
      EngineName: postgres
      MajorEngineVersion: "15"
      OptionGroupDescription: !Sub "${AWS::StackName} options group"
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-Topic"
        - Key: CostTag
          Value: !Ref AWS::StackName
        - Key: AppManagerCFNStackKey
          Value: !Ref AWS::StackName