on:
  workflow_dispatch: {}
name: NAT instance deploy
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: nat_instance
    name: Deploy NAT instance
    permissions:
      id-token: write
      contents: read
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v4
      - id: login
        name: Login to AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.ROLE_ARN }}
          aws-region: ${{ vars.REGION_NAME }}
      - id: deploy
        name: Deploy stack
        run: >-
          aws cloudformation deploy --template-file
          nat_instance/formation.yml
          --stack-name ${{ secrets.STACK_NAME }}
          --role-arn ${{ secrets.CLOUDFORMATION_ROLE }}
          --no-fail-on-empty-changeset
          --tags Name=${{ secrets.STACK_NAME }}
          CostTag=${{ secrets.STACK_NAME }}
          AppManagerCFNStackKey=${{ secrets.STACK_NAME }}
          --parameter-overrides
          ImageId=${{ secrets.AMI_ID }}
          InstanceProfile=${{ secrets.INSTANCE_PROFILE }}
          VpcId=${{ secrets.VPC_ID }}
          SubnetId=${{ secrets.SUBNET_ID }}
          VpcCidr=${{ secrets.VPC_CIDR }}
          RouteTableId1=${{ secrets.ROUTE_TABLE_1 }}
          RouteTableId2=${{ secrets.ROUTE_TABLE_2 }}
          RouteTableId3=${{ secrets.ROUTE_TABLE_3 }}